package openapiproject

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/printer"
	"go/types"
	"log/slog"
	"reflect"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

const SERVER_INTERFACE = "ServerInterface"

const HEADER_COMMENT = "// This file is generated by github.com/baudii/ada-ai DO NOT EDIT\n"

type MethodInfo struct {
	Name    string
	Params  []ParamInfo
	Imports map[string]string
}

type FieldInfo struct {
	Name string
	Type string
	Tags reflect.StructTag
	Doc  string
}

type ParamInfo struct {
	Name       string
	MethodName string
	Type       string
	IsStruct   bool
	StructName string
	Fields     []FieldInfo
	TypeSpec   *ast.TypeSpec
}

func PascalToSnake(s string) string {
	var out []rune

	for i, r := range s {
		if unicode.IsUpper(r) {
			if i != 0 {
				out = append(out, '_')
			}
			out = append(out, unicode.ToLower(r))
		} else {
			out = append(out, r)
		}
	}

	return string(out)
}

func getMethodInfo(method *types.Func, pkg *packages.Package) MethodInfo {
	sig := method.Type().(*types.Signature)
	var params []ParamInfo

	typeSpecs := map[string]*ast.TypeSpec{}
	for _, f := range pkg.Syntax {
		for _, decl := range f.Decls {
			if gd, ok := decl.(*ast.GenDecl); ok {
				for _, spec := range gd.Specs {
					if ts, ok := spec.(*ast.TypeSpec); ok {
						typeSpecs[ts.Name.Name] = ts
					}
				}
			}
		}
	}

	imports := map[string]string{}
	qual := makeQualifier(pkg.TypesInfo, imports)

	for i := 0; i < sig.Params().Len(); i++ {
		pv := sig.Params().At(i)

		param := ParamInfo{
			Name: pv.Name(),
			Type: types.TypeString(pv.Type(), qual),
		}

		if named, ok := pv.Type().(*types.Named); ok {
			if st, ok := named.Underlying().(*types.Struct); ok {
				param.IsStruct = true
				param.StructName = named.Obj().Name()

				if ts, ok := typeSpecs[named.Obj().Name()]; ok {
					param.TypeSpec = ts

					if structNode, ok := ts.Type.(*ast.StructType); ok {
						for idx, field := range structNode.Fields.List {
							fi := FieldInfo{
								Name: field.Names[0].Name,
								Type: types.TypeString(st.Field(idx).Type(), qual),
							}

							if field.Tag != nil {
								tag := reflect.StructTag(field.Tag.Value[1 : len(field.Tag.Value)-1])
								fi.Tags = tag
							}

							if field.Doc != nil {
								for _, c := range field.Doc.List {
									fi.Doc += c.Text + "\n"
								}
							}

							param.Fields = append(param.Fields, fi)
						}
					}
				}
			}
		}

		params = append(params, param)
	}

	methodInfo := MethodInfo{
		Name:    method.Name(),
		Params:  params,
		Imports: imports,
	}

	return methodInfo
}

func makeQualifier(info *types.Info, imports map[string]string) types.Qualifier {
	return func(pkg *types.Package) string {
		for _, obj := range info.Uses {
			if pkgName, ok := obj.(*types.PkgName); ok && pkgName.Imported() == pkg {
				name := pkgName.Name()
				imports[name] = pkg.Path()
				return name
			}
		}
		name := pkg.Name()
		imports[name] = pkg.Path()
		return name
	}
}

func writeComments(out *strings.Builder, cg *ast.CommentGroup, methodInfo MethodInfo, pkg *packages.Package) {
	out.WriteString(HEADER_COMMENT)
	fmt.Fprintf(out, "//\n// Handler for %s method\n", methodInfo.Name)

	if cg != nil {
		out.WriteString("//\n// DESCRIPTION:\n")
		for _, c := range cg.List {
			out.WriteString(c.Text + "\n")
		}
	}

	out.WriteString("//\n// PARAMETERS:\n")
	for _, prm := range methodInfo.Params {
		fmt.Fprintf(out, "//   %s %s\n", prm.Name, prm.Type)
	}

	for _, prm := range methodInfo.Params {
		if prm.IsStruct && prm.TypeSpec != nil {
			ts := prm.TypeSpec

			fmt.Fprintf(out, "//\n// STRUCT %s DEFINITION:\n", prm.StructName)

			var leadingDoc *ast.CommentGroup

			if ts.Doc != nil {
				leadingDoc = ts.Doc
			} else {
				for _, file := range pkg.Syntax {
					if cg := findLeadingComment(ts, file); cg != nil {
						leadingDoc = cg
						break
					}
				}
			}

			if leadingDoc != nil {
				for _, c := range leadingDoc.List {
					out.WriteString("// " + c.Text + "\n")
				}
			}

			var buf bytes.Buffer
			err := printer.Fprint(&buf, pkg.Fset, ts)
			if err != nil {
				continue
			}

			for line := range strings.SplitSeq(buf.String(), "\n") {
				out.WriteString("// " + line + "\n")
			}
		}
	}
}

func processServerInterfaceMethods(
	ctx context.Context,
	logger *slog.Logger,
	pkgs []*packages.Package,
	callback func(context.Context, MethodInfo, *ast.CommentGroup, *packages.Package) error,
) {
	for _, pkg := range pkgs {
		scope := pkg.Types.Scope()

		obj := scope.Lookup(SERVER_INTERFACE)
		if obj == nil {
			continue
		}

		if iface, ok := obj.Type().Underlying().(*types.Interface); ok {
			for method := range iface.Methods() {
				for _, file := range pkg.Syntax {
					ast.Inspect(
						file,
						func(n ast.Node) bool {
							td, ok := n.(*ast.TypeSpec)
							if !ok || td.Name.Name != SERVER_INTERFACE {
								return true
							}

							if ifaceType, ok := td.Type.(*ast.InterfaceType); ok {
								for _, f := range ifaceType.Methods.List {
									if len(f.Names) > 0 && f.Names[0].Name == method.Name() {
										methodInfo := getMethodInfo(method, pkg)
										err := callback(ctx, methodInfo, f.Doc, pkg)
										if err != nil {
											logger.Error("failed to materialize handler", "method", method.Name(), "error", err)
										}
									}
								}
							}
							return false
						})
				}
			}
		}
	}
}

func findLeadingComment(ts *ast.TypeSpec, file *ast.File) *ast.CommentGroup {
	tsPos := int(ts.Pos())

	var best *ast.CommentGroup
	bestEnd := -1

	for _, cg := range file.Comments {
		end := int(cg.End())

		if end < tsPos {
			if end > bestEnd {
				best = cg
				bestEnd = end
			}
		}
	}

	return best
}
