package openapiproject

import (
	"context"
	"fmt"
	"go/ast"
	"go/types"
	"os"
	"reflect"
	"strings"
	"unicode"

	"github.com/baudii/ada-ai/internal/app/codeanalyzer"
	"golang.org/x/tools/go/packages"
)

const SERVER_INTERFACE = "ServerInterface"

const HEADER_COMMENT = "// This file is generated by github.com/baudii/ada-ai DO NOT EDIT\n\n"

type MethodInfo struct {
	Name    string
	Docs    []string
	Params  []ParamInfo
	Returns []ParamInfo
	Imports map[string]string
}

type FieldInfo struct {
	Name     string
	Type     string
	Tags     reflect.StructTag
	Docs     []string
	Comments []string
}

type StructInfo struct {
	Name   string
	Docs   []string
	Fields []FieldInfo
}

type ParamInfo struct {
	Name       string
	Type       string
	StructInfo *StructInfo
}

func PascalToSnake(s string) string {
	var out []rune

	for i, r := range s {
		if unicode.IsUpper(r) {
			if i != 0 {
				out = append(out, '_')
			}
			out = append(out, unicode.ToLower(r))
		} else {
			out = append(out, r)
		}
	}

	return string(out)
}

func Extract[T ast.Expr](path, filter string) (string, error) {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return "", nil
	}
	f, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read file: %w", err)
	}

	res, err := codeanalyzer.ExtractTypesOf[T](string(f), filter)
	if err != nil {
		return "", fmt.Errorf("extract type of %T: %w", *new(T), err)
	}

	return res, nil
}

func getMethodInfo(method *types.Func, pkg *packages.Package, doc *ast.CommentGroup) MethodInfo {
	sig := method.Type().(*types.Signature)
	var params, returns []ParamInfo

	typeSpecs := map[string]*ast.TypeSpec{}
	for _, f := range pkg.Syntax {
		for _, decl := range f.Decls {
			if gd, ok := decl.(*ast.GenDecl); ok {
				for _, spec := range gd.Specs {
					if ts, ok := spec.(*ast.TypeSpec); ok {
						ts.Doc = gd.Doc
						typeSpecs[ts.Name.Name] = ts
					}
				}
			}
		}
	}

	imports := map[string]string{}
	qual := makeQualifier(pkg.TypesInfo, imports)

	for i := 0; i < sig.Params().Len(); i++ {
		pv := sig.Params().At(i)
		params = append(params, getParamInfo(pv, qual, typeSpecs))
	}

	for i := 0; i < sig.Results().Len(); i++ {
		rv := sig.Results().At(i)
		returns = append(returns, getParamInfo(rv, qual, typeSpecs))
	}

	docs := []string{}
	for _, v := range doc.List {
		docs = append(docs, v.Text)
	}

	methodInfo := MethodInfo{
		Name:    method.Name(),
		Docs:    docs,
		Params:  params,
		Returns: returns,
		Imports: imports,
	}

	return methodInfo
}

func getParamInfo(pv *types.Var, qual types.Qualifier, typeSpecs map[string]*ast.TypeSpec) ParamInfo {
	param := ParamInfo{
		Name: pv.Name(),
		Type: types.TypeString(pv.Type(), qual),
	}

	if named, ok := pv.Type().(*types.Named); ok {
		if st, ok := named.Underlying().(*types.Struct); ok {
			structInfo := StructInfo{
				Name: named.Obj().Name(),
			}

			if ts, ok := typeSpecs[structInfo.Name]; ok {
				if structNode, ok := ts.Type.(*ast.StructType); ok {
					structInfo.Docs = []string{}
					if ts.Doc != nil {
						for _, c := range ts.Doc.List {
							structInfo.Docs = append(structInfo.Docs, c.Text)
						}
					}

					structInfo.Fields = []FieldInfo{}
					for idx, field := range structNode.Fields.List {
						fi := FieldInfo{
							Name: field.Names[0].Name,
							Type: types.TypeString(st.Field(idx).Type(), qual),
						}

						if field.Tag != nil {
							tag := reflect.StructTag(field.Tag.Value[1 : len(field.Tag.Value)-1])
							fi.Tags = tag
						}

						if field.Doc != nil {
							for _, c := range field.Doc.List {
								fi.Docs = append(fi.Docs, c.Text)
							}
						}

						structInfo.Fields = append(structInfo.Fields, fi)
					}
				}
			}

			param.StructInfo = &structInfo
		}
	}
	return param
}

func makeQualifier(info *types.Info, imports map[string]string) types.Qualifier {
	return func(pkg *types.Package) string {
		for _, obj := range info.Uses {
			if pkgName, ok := obj.(*types.PkgName); ok && pkgName.Imported() == pkg {
				name := pkgName.Name()
				imports[name] = pkg.Path()
				return name
			}
		}
		name := pkg.Name()
		imports[name] = pkg.Path()
		return name
	}
}

func writeHandlerGoDoc(out *strings.Builder, methodInfo MethodInfo) {
	fmt.Fprintf(out, "// %s handles %s\n", methodInfo.Name, strings.Trim(methodInfo.Docs[1], "()/ "))

	out.WriteString("//\n// DESCRIPTION:\n")
	out.WriteString(methodInfo.Docs[0] + "\n")

	out.WriteString("//\n// PARAMETERS:\n")
	for _, prm := range methodInfo.Params {
		fmt.Fprintf(out, "//   %s %s\n", prm.Name, prm.Type)
	}

	for _, prm := range methodInfo.Params {
		structInfo := prm.StructInfo
		if structInfo != nil {
			out.WriteString("//\n")
			for _, c := range prm.StructInfo.Docs {
				out.WriteString("// " + c + "\n")
			}

			fmt.Fprintf(out, "// type %s struct {\n", structInfo.Name)
			for _, field := range structInfo.Fields {
				for _, doc := range field.Docs {
					out.WriteString("// \t" + doc + "\n")
				}
				fmt.Fprintf(out, "// \t%s %s", field.Name, field.Type)
				if field.Tags != "" {
					out.WriteString("// " + string(field.Tags))
				}
				out.WriteString("// \n")
			}
			out.WriteString("// }\n")
		}
	}
}

func (o *OpenAPIProject) processServerInterfaceMethods(
	ctx context.Context,
	callback func(context.Context, MethodInfo) error,
) error {
	cfg := &packages.Config{
		Mode: packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports,
		Dir:  o.outputDir,
	}

	pkgs, err := packages.Load(cfg, fmt.Sprintf("%s/%s/%s", o.moduleName, INTERNAL_FOLDER, API_FOLDER))
	if err != nil {
		return fmt.Errorf("load package: %w", err)
	}

	for _, pkg := range pkgs {
		scope := pkg.Types.Scope()

		obj := scope.Lookup(SERVER_INTERFACE)
		if obj == nil {
			continue
		}

		if iface, ok := obj.Type().Underlying().(*types.Interface); ok {
			for method := range iface.Methods() {
				for _, file := range pkg.Syntax {
					ast.Inspect(
						file,
						func(n ast.Node) bool {
							td, ok := n.(*ast.TypeSpec)
							if !ok || td.Name.Name != SERVER_INTERFACE {
								return true
							}

							if ifaceType, ok := td.Type.(*ast.InterfaceType); ok {
								for _, f := range ifaceType.Methods.List {
									if len(f.Names) > 0 && f.Names[0].Name == method.Name() {
										methodInfo := getMethodInfo(method, pkg, f.Doc)
										err := callback(ctx, methodInfo)
										if err != nil {
											o.logger.Error("failed to materialize handler", "method", method.Name(), "error", err)
										}
									}
								}
							}
							return false
						})
				}
			}
		}
	}
	return nil
}
