package openapiproject

import (
	"context"
	"fmt"
)

type llmResponse struct {
	functionBody string
	usedRepo     string
	comments     string
}

func ParseLLMResponse(body string) (*llmResponse, error) {
	fmt.Println(body)
	return nil, nil
}

func ValidateFunctionBody(body string) error {
	// reader := strings.NewReader(body)
	// scanner := bufio.NewScanner(reader)
	// // Body is generated by LLM, so we must check and remove mistakes such as:
	// //   * Existing function declaration
	// //   * Markdown symbols in the beginning and end
	// //   * Empty lines

	// validBody := strings.Builder{}

	// for scanner.Scan() {
	// 	line := scanner.Text()
	// 	if strings.HasPrefix(line, "func ") {
	// 		continue
	// 	}
	// 	if strings.Contains(line, "```") {
	// 		strings.Replace(line, "```")
	return nil
}

func (o *OpenAPIProject) ApplyResponse(ctx context.Context, content, interfaces []byte) error {
	// f, err := os.ReadFile(path)
	// if err != nil {
	// 	return err
	// }
	ParseLLMResponse(string(content))
	return nil
}
